AWSTemplateFormatVersion: "2010-09-09"
Description: Role and Policy
Resources:
  CommonRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: commonrole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies: 
        - PolicyName: commonPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'dynamodb:*'
                  - 's3:*'
                  - 'logs:*'
                Resource: '*'
Outputs:
  CommonRoleArn:  
    Value: !GetAtt CommonRole.Arn 
    Export:
      Name: CommonRole