AWSTemplateFormatVersion: "2010-09-09"
Description: Creating S3 bucket 
Parameters:
  BucketName: 
    Type: String 
Resources:
  S3Bucket: 
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref BucketName
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:*
            Function: !GetAtt deploylambda
            Filter:
              S3Key:
                Rules:
                - Name: suffix
                  Value: .json
Outputs:
  S3BucketArn:  
    Value: !GetAtt S3Bucket.Arn 
    Export:
      Name: S3Bucket