AWSTemplateFormatVersion: '2010-09-09'
Description: S3 and Lambda function
Resources:
  S3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref BucketName
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:*
            Function: !GetAtt deploylambda
            Filter:
              S3Key:
                Rules:
                - Name: suffix
                  Value: .json
    DependsOn:
     - LambdaInvoke
  LambdaFunction: 
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: deploy      
      Handler: index.lambda_handler
      Role: !ImportValue CommonRole
      Code:
        ZipFile: !Sub |
          import json
          import boto3
          s3_client = boto3.client('s3')
          dynamodb = boto3.resource('dynamodb')
          def lambda_handler(event, context):
            bucket = event['Records'][0]['s3']['bucket']['name']
            json_file_name = event['Records'][0]['s3']['object']['key']
            json_object = s3_client.get_object(Bucket=bucket,Key=json_file_name)
            jsonFileReader = json_object['Body'].read()
            jsonDict = json.loads(jsonFileReader)
            table = dynamodb.Table('employeetable')
            table.put_item(Item=jsonDict)
            return {
              'statusCode': 200,
              'body': json.dumps('Success!')
            }
      Runtime: python3.6

  LambdaInvoke:
    Type: AWS::Lambda::Permission
    Properties: 
      Action: lambda:InvokeFunction
      FunctionName: !Ref LambdaFunction
      Principal: s3.amazonaws.com
      SourceAccount: !Ref 'AWS::AccountId'
      SourceArn: !Sub 'arn:aws:s3:::${BucketName}'      
